export const zh = {
  nav: { home: "首页", capabilities: "能力", results: "成果", methodology: "方法论", contact: "联系" },
  common: { skip: "跳至正文", navigation: "主导航", home: "CIEN — 首页", menu: "菜单", close: "关闭菜单", menuDescription: "浏览页面、切换语言或下载简历。", language: "界面语言", switchZh: "切换为中文", switchEn: "Switch to English", resume: "简历下载", resumeNote: "中文简历 · PDF", viewCase: "查看完整案例", viewAll: "全部成果", next: "下一页", back: "返回成果", previous: "上一阶段", following: "下一阶段", stage: "阶段", selectStage: "选择一个阶段，查看具体判断与交付", expand: "展开职责", collapse: "收起职责", context: "背景", ownership: "我负责什么", decision: "关键判断", system: "建立的方法", evidence: "实际证据", scope: "责任范围", evaluate: "评估", coordinate: "协同", output: "产出", input: "输入", nextAction: "下一步", outcome: "结果", learning: "复盘", diagnosis: "诊断", execution: "推进与执行", phone: "电话", email: "邮箱", top: "返回顶部", allStages: "查看完整阶段", capabilities: "了解能力范围", results: "查看实际成果", scroll: "向下探索", proofNote: "曜闪科技任职期间的累计工作记录，截至 2026 年 8 月 31 日；各项对应不同合作阶段，不代表同一转化漏斗。", imageNote: "工作氛围图；图中屏幕不作为业务数据证据。" },
  hero: { role: "海外社媒与 Creator / KOL 运营", thesis: ["把碎片化执行，", "转化为可复用、可交付的运营系统。"], principles: "北美市场 · 系统搭建 · 商业判断 · 项目交付", location: "美国 / 北美" },
  home: { operator: "01 / 运营视角", operatorTitle: "判断，让执行有方向。", operatorIntro: "独立负责北美社媒与 Creator 合作，把受众与商业信号转化为具体决策、可执行流程和最终交付。", chain: "02 / 全链路 Ownership", chainTitle: "从受众，到下一次合作。", chainIntro: "一个 Owner，贯穿 14 个阶段。独立做判断，也明确每个协作方的责任和下一步。", proof: "03 / 关键证据", proofAside: "让结果，回到判断。", operate: "04 / 我能负责什么", operateTitle: "六个能力领域，一个交付闭环。", work: "05 / 代表项目", workTitle: "改变了什么，如何做到。", experience: "06 / 实际经历", experienceTitle: "在不同约束下，把工作做成。", ai: "07 / AI 辅助工作流", aiTitle: "工具辅助，判断由我负责。", aiTools: "日常使用 ChatGPT / Claude。", aiPlaceholder: "[AI WORKFLOW COPY REQUIRES CIEN APPROVAL]", contact: "08 / 联系与简历", contactTitle: "聊聊你需要推进的工作。", nextTitle: "看看我能\n独立负责什么。", principles: "系统搭建 · 商业判断 · 项目交付" },
  pages: {
    capabilities: { eyebrow: "01 / 能力", title: "Cien 能\n独立负责什么？", intro: "从海外社媒到 Creator / KOL 全链路，在单人 Owner 环境下做判断、搭系统，并协调资源完成交付。", bodyTitle: "责任，不止于任务。", bodyIntro: "选择一个领域，查看我如何判断、组织和交付。", nextTitle: "看看这些能力，\n带来了什么改变。" },
    results: { eyebrow: "02 / 成果", title: "实际改变、搭建\n并交付了什么？", intro: "受众校准、Creator Pipeline、多平台内容与社区机制。每个结果，都有相应的判断与执行路径。", bodyTitle: "四个项目，四种改变。", bodyIntro: "三个关键结果，四个项目。选择项目，查看判断与交付过程。", nextTitle: "看结果背后，\n如何做判断。" },
    methodology: { eyebrow: "03 / 方法论", title: "把判断，\n变成下一步。", intro: "先明确问题，再确定优先级。让每一次执行有依据、每一个节点有 Owner、每一轮复盘有下一步。", bodyTitle: "一套持续运转的工作循环。", bodyIntro: "从诊断到迭代，选择任一阶段，查看输入、评估、决策和实际产出。", nextTitle: "把下一个项目，\n推进到交付。" },
    contact: { eyebrow: "04 / 联系", title: "从一次对话，\n开始下一段交付。", intro: "海外社媒运营 · Creator / KOL 运营\n美国 / 北美市场", bodyTitle: "直接联系", bodyIntro: "欢迎交流岗位机会、职责范围与项目需求。", nextTitle: "回到首页。" },
  },
  operator: [
    { id: "signal", title: "信号", en: "SIGNAL", text: "看业务目标、受众地域、内容反馈和合作数据，先识别真正需要解决的问题。", output: "明确问题与判断依据" },
    { id: "judgment", title: "判断", en: "JUDGMENT", text: "衡量匹配度、成本和交付风险，确定优先级；对不值得推进的合作及时说停。", output: "确定方向、边界与取舍" },
    { id: "system", title: "系统", en: "SYSTEM", text: "将判断落实为 Pipeline、SOP、Checklist、Owner 和 Next Action，让项目可以持续推进。", output: "可复用的执行路径" },
    { id: "delivery", title: "交付", en: "DELIVERY", text: "协调库存、物流、内容、链接与付款，解决阻塞，并跟进上线、数据回收和合作复盘。", output: "上线、衡量与闭环" },
  ],
  ownership: [
    { id: "audience", title: "受众", en: "AUDIENCE", evaluate: "受众地域、品类兴趣与北美目标市场的匹配度。", decision: "匹配则推进，边缘匹配降低优先级，不匹配则 PASS。", coordinate: "与业务负责人确认目标市场和产品方向。", output: "清晰的受众标准与内容定位。" },
    { id: "content", title: "内容", en: "CONTENT", evaluate: "住宅场景、Hook、文案和平台反馈能否传递一致的北美信号。", decision: "确定内容方向与本轮 A/B Testing 变量。", coordinate: "对齐设计、产品与网站的素材和信息。", output: "内容计划、素材需求与测试假设。" },
    { id: "sourcing", title: "Creator 开发", en: "CREATOR SOURCING", evaluate: "Creator 的品类关联、内容风格及可触达性。", decision: "确定开发方向、沟通顺序与优先级。", coordinate: "向 Creator 发送清晰的合作意向并跟进回复。", output: "可持续更新的候选 Pipeline。" },
    { id: "screening", title: "筛选", en: "SCREENING", evaluate: "Audience、近期内容表现、互动质量和数据真实性。", decision: "区分值得深聊、需要补充数据与不适合的对象。", coordinate: "向 Creator 获取缺失的受众与近期数据。", output: "有依据的筛选结论。" },
    { id: "commercial", title: "商业判断", en: "COMMERCIAL JUDGMENT", evaluate: "受众、近期表现、报价、产品匹配和交付成本。", decision: "推进、谈价、暂停或 PASS；不只看粉丝数。", coordinate: "对齐业务负责人与 Creator 的合作预期。", output: "可解释的合作价值判断。" },
    { id: "negotiation", title: "谈判", en: "NEGOTIATION", evaluate: "报价与交付内容是否匹配，合作边界是否清楚。", decision: "确定可接受的合作模式、价格与内容要求。", coordinate: "与 Creator 确认交付、排期及付款约定。", output: "明确的合作条件与下一步。" },
    { id: "seeding", title: "选品与寄样", en: "PRODUCT SEEDING", evaluate: "产品适配、库存、收件信息与拍摄场景。", decision: "选择合适产品并确认可执行的寄样安排。", coordinate: "对接采购、仓库、客服与 Creator。", output: "确认选品、地址与发货要求。" },
    { id: "logistics", title: "物流", en: "LOGISTICS", evaluate: "运输状态、清关、破损补发与交付时间。", decision: "识别阻塞，确定处理负责人和下一动作。", coordinate: "跟进仓储、工厂、物流与客服，并统一更新 Creator。", output: "签收确认或明确的异常解决方案。" },
    { id: "review", title: "内容审核", en: "CONTENT REVIEW", evaluate: "产品信息、内容质量、品牌要求与 Creator 自身风格。", decision: "批准或提出具体修改点，避免泛泛要求重拍。", coordinate: "与 Creator、设计和业务方确认修改。", output: "可上线的内容、Caption 与 Title。" },
    { id: "launch", title: "上线", en: "LAUNCH", evaluate: "内容、链接、折扣码与排期是否就绪。", decision: "确认上线，或先处理尚未关闭的依赖项。", coordinate: "对接 Creator 与网站运营核实最终信息。", output: "上线链接和发布记录。" },
    { id: "tracking", title: "Tracking", en: "TRACKING", evaluate: "Tracking Link、Discount Code 和流量归因信号。", decision: "检查缺失或异常的追踪项。", coordinate: "与网站运营和 Creator 核对链接使用情况。", output: "可以追踪的流量与订单线索。" },
    { id: "performance", title: "数据回收", en: "PERFORMANCE COLLECTION", evaluate: "内容表现、Audience、Referral Traffic 与转化信号。", decision: "区分曝光、互动、引流和转化价值。", coordinate: "向 Creator 收集数据，并对照网站表现。", output: "项目表现记录与复盘依据。" },
    { id: "payment", title: "付款", en: "PAYMENT", evaluate: "交付完成情况与约定的结算条件。", decision: "确认结算节点，追踪未解决的问题。", coordinate: "对接财务与 Creator，统一说明付款状态。", output: "付款推进与项目结算闭环。" },
    { id: "repeat", title: "再次合作判断", en: "REPEAT-PARTNERSHIP DECISION", evaluate: "受众质量、交付可靠性、转化潜力与长期合作价值。", decision: "继续合作、调整方案、保留观察或停止推进。", coordinate: "对齐业务负责人，并更新 Creator 合作状态。", output: "下一轮优先级与可复用经验。" },
  ],
  proof: {
    primary: [
      { value: "80", suffix: "%+", title: "核心平台北美受众", context: "通过统一北美住宅场景与内容信号持续校准；不含长期投放广告的 YouTube。", href: "/results/audience-recalibration" },
      { value: "8,000", suffix: "+", title: "累计开发 Creator", context: "从 0 建立美国 Creator Pipeline，获得 3,000+ 位 Creator 回复。", href: "/results/creator-pipeline" },
      { value: "42", suffix: "", title: "进入正式合作并寄样", context: "持续推进内容、上线、Tracking 与结算，回收 42 份内容，34 个项目上线。", href: "/results/creator-pipeline" },
    ],
    secondary: [ { value: "90%+", label: "TikTok 北美受众" }, { value: "3,000+", label: "回复 Creator 人数" }, { value: "42", label: "内容回收" }, { value: "34", label: "项目上线" } ],
    order: "通过追踪链接与上线数据跟进站外引流；不公开销售金额。",
  },
  capabilities: [
    { id: "social", title: "海外社媒运营", en: "SOCIAL OPERATIONS", scope: "独立负责 TikTok、Instagram、Facebook、YouTube 与 Pinterest 的定位、内容和复盘。", decision: "按受众质量、Referral Traffic 与转化信号判断平台优先级。", system: "同一素材复用，按平台重写 Hook、标题、链接、CTA 与形式，持续 A/B Testing。", evidence: "核心平台北美受众 80%+；TikTok 90%+。", href: "/results/audience-recalibration" },
    { id: "creator", title: "Creator / KOL 运营", en: "CREATOR OPERATIONS", scope: "独立搭建并运行美国 Creator 从开发到结算、再合作判断的全链路。", decision: "评估 Audience、数据真实性、报价、内容质量与合作价值。", system: "分阶段 Pipeline、筛选标准、合作跟进与内容审核流程。", evidence: "开发 8,000+ Creator，42 位进入正式合作并寄样。", href: "/results/creator-pipeline" },
    { id: "systems", title: "运营系统", en: "OPERATING SYSTEMS", scope: "把内容生产、合作推进与上线要求整理成可重复执行的流程。", decision: "识别重复工作、责任空白与最容易出错的交接点。", system: "SOP、Checklist、阶段状态、Owner 与 Next Action。", evidence: "从 0 建立 Creator Pipeline 与多平台内容执行机制。", href: "/results/social-operations" },
    { id: "delivery", title: "项目交付", en: "PROJECT DELIVERY", scope: "跟进选品、寄样、物流、拍摄、审核、上线、数据与付款。", decision: "确认依赖是否就绪，判断阻塞原因与推进顺序。", system: "逐项目跟进节点、问题负责人和下一动作，直到闭环。", evidence: "回收 24 份内容，推动 8 个项目上线。", href: "/results/creator-pipeline" },
    { id: "judgment", title: "商业判断", en: "COMMERCIAL JUDGMENT", scope: "评估 Creator 合作成本、产品匹配、交付风险及持续合作价值。", decision: "推进、谈价、暂停或 PASS；策略变化时按阶段和价值重排 Pipeline。", system: "结合 Audience、近期表现、互动、内容质量与成本形成判断依据。", evidence: "合作推进覆盖报价谈判、阶段取舍与再次合作判断。", href: "/results/creator-pipeline" },
    { id: "cross", title: "跨部门推进与交付", en: "CROSS-FUNCTIONAL DELIVERY", scope: "协调管理层、客服、财务、采购仓储、物流、设计、网站运营与 Creator。", decision: "先确认问题和 Owner，再统一对外沟通，避免信息断层。", system: "异常识别 → 对接负责人 → 跟进解决 → 更新 Creator → 恢复下一节点。", evidence: "处理库存、清关、损坏补发、内容修改、链接与付款等异常。", href: "/results/creator-pipeline" },
  ],
  cases: [
    { slug: "audience-recalibration", index: "01", title: "北美受众校准", category: "受众 / 内容判断", result: "80%+", resultLabel: "核心平台北美受众", context: "接手时账号更新不稳定、自然推荐弱，受众地域与北美目标市场不匹配。", ownership: "独立重建内容定位、北美住宅场景和语义信号，持续调整 Hook、文案、Hashtag、发布时间与结构。", decision: "先恢复稳定发布与一致信号，再进行增长测试；把受众质量放在单条播放量之前。", outcome: "除长期投放广告的 YouTube 外，核心平台北美受众达到 80%+，TikTok 达 90%+。", diagnosis: "全球分散的受众说明平台识别到的内容信号与目标市场存在偏差，单次发帖无法完成纠正。", system: "建立稳定内容方向，以北美住宅与家居场景形成一致信号，通过 A/B Testing 和平台数据复盘调整。", execution: "统一视觉与语义，按平台调整 Hook、文案、Hashtag 与发布时间，持续查看受众地域反馈。", learning: "受众校准依靠持续一致的内容信号与复盘；播放量需要和受众匹配度一起判断。" },
    { slug: "creator-pipeline", index: "02", title: "0 → 1 Creator 合作系统", category: "Creator / 全链路 Ownership", result: "8,000+", resultLabel: "累计开发 Creator", context: "品牌希望通过美国 Creator 扩大影响力并验证带货，但没有专人、统一标准或完整合作流程。", ownership: "独立负责开发、筛选、商业判断、谈判、寄样、内容审核、上线、Tracking、数据回收、付款与再次合作判断。", decision: "难点不止是找到人，更在于筛选质量、合作成本、交付可靠性与项目闭环。", outcome: "截至 2026 年 8 月 31 日，开发 8,000+ Creator，获得 3,000+ 位 Creator 回复；42 位合作寄样，回收 42 份内容、34 个项目上线。各项为不同合作阶段的累计记录。", diagnosis: "开发、交付与结算缺少连续流程，已确认的合作仍可能卡在库存、物流、内容或付款环节。", system: "独立搭建全套合作标准，涵盖开发邮件、品牌介绍与选品、付费及置换 Brief、合同、寄样物流、内容审核、上线追踪与数据复盘；通过 Creator 资料库和项目台账记录阶段、Checklist 与下一步。", execution: "审核 Audience 与近期数据，谈判合作条件，协调选品物流，给出具体内容修改点，核对 Tracking Link、Discount Code 与排期，回收数据并推进付款。", learning: "从追求开发量转向更重视筛选准确度、交付可靠性、转化潜力和持续合作价值。" },
    { slug: "social-operations", index: "03", title: "多平台内容运营体系", category: "内容系统 / 渠道判断", result: "5", resultLabel: "平台由一人独立运营", context: "五个平台由一人负责，完全独立生产效率不足，简单复制粘贴又无法适配渠道特点。", ownership: "运营 TikTok、Instagram、Facebook、YouTube、Pinterest，覆盖内容定位、素材制作、发布与数据复盘。", decision: "素材可以复用，内容包装必须适配平台；渠道优先级要联系 Audience、Referral Traffic 与转化。", outcome: "Pinterest 主页月浏览量由 8.9 万提升至最新约 19 万；5—8 月 YouTube 来源会话从约 5.2K 增至 7.1K，Pinterest 从约 2.5K 增至 3.3K。月浏览量为最新主页快照；来源会话含广告贡献，不等于订单。", diagnosis: "单看粉丝和播放量，无法分清各平台在品牌曝光、互动、引流与转化中的不同作用。", system: "建立可复用素材体系，按平台调整 Hook、标题、链接、CTA 和内容形式。", execution: "从选题、脚本、拍摄剪辑到文案发布形成执行流程；结合内容反馈和网站表现持续调整。", learning: "单人运营的效率来自可复用系统；不同平台需要不同的价值判断标准。" },
    { slug: "community-system", index: "04", title: "Facebook 社区与 Member Day", category: "社区 / 机制验证", result: "0 → 1", resultLabel: "社区与会员日机制", context: "品牌需要在平台曝光之外，增加用户沉淀、重复触达与活动承接场景。", ownership: "从 0 搭建 Facebook Group，并建立固定 Member Day 机制，连接内容、优惠与社区承接。", decision: "先验证内容、活动与社区能否形成闭环，再扩大规模。", outcome: "完成首批用户沉淀，并获得首批订单验证。", diagnosis: "曝光之后缺少持续触达用户的场景，需要让内容与活动有稳定的承接位置。", system: "以 Facebook Group 承接品牌用户和活动，通过固定 Member Day 建立可重复的运营节奏。", execution: "搭建社区，配合 Facebook 内容发布与会员日活动，追踪用户积累和订单信号。", learning: "社区早期先证明机制能跑通，再讨论规模；用户积累与订单验证应同时关注。" },
  ],
  experience: [
    { company: "曜闪科技", period: "2026.05 — 至今", role: "海外社媒运营 · 单人 Owner", summary: "独立负责五平台社媒与美国 Creator Pipeline，从内容定位推进到合作结算。", details: "完成北美受众校准；从 0 搭建 Creator 全链路流程；协调管理层、客服、财务、采购仓储、物流、设计、网站运营与 Creator，解决交付依赖和项目异常。", signal: "北美市场 · Creator 系统 · 项目 Ownership" },
    { company: "深圳市鹿优科技有限公司", period: "2026.03 — 2026.05", role: "海外社媒运营 · 多客户项目", summary: "最多同时负责 3 个客户，覆盖家居、集成房屋与窗帘行业。", details: "独立完成定位、市场与竞品研究、策略、选题脚本、拍摄剪辑、发布、分析与客户汇报；建立个人执行 SOP，产出高表现内容并带来海外询盘。", signal: "多客户交付 · 内容全流程 · 持续复盘" },
    { company: "广州知贤道远信息服务有限公司", period: "2025.02 — 2026.02", role: "用户服务与课程交付", summary: "在高目标压力下，锻炼客户需求判断、沟通与结果交付能力。", details: "负责用户服务、课程交付、客户关系与续费推进；2025 年度续费取得小组及团队第一。这段经历强化了目标意识与持续执行能力。", signal: "客户判断 · 沟通 · 高压执行" },
  ],
  methodology: {
    pipelineTitle: "Creator Pipeline：五个推进阶段。", pipelineIntro: "从寻找合适的人，到完成交付与结算。阶段清楚，判断和责任才不会断开。", cycle: [
      { id: "audit", title: "诊断", en: "AUDIT", input: "账号现状、受众、内容、合作进展与业务目标。", evaluate: "受众错位、更新断层、数据异常和交付阻塞。", decision: "先明确真正需要解决的问题。", output: "有依据的问题清单与工作起点。", nextAction: "定义目标与责任边界。" },
      { id: "define", title: "定义", en: "DEFINE", input: "诊断结论与市场、产品要求。", evaluate: "目标市场、受众、内容方向和合作适配度。", decision: "确定要服务谁、解决什么问题、谁来负责。", output: "目标、范围、Owner 与判断标准。", nextAction: "比较优先级与资源限制。" },
      { id: "prioritize", title: "排序", en: "PRIORITIZE", input: "候选内容、平台、Creator 与在途项目。", evaluate: "业务价值、成本、风险、当前阶段与资源依赖。", decision: "推进高价值和已确认项目，暂停不匹配事项。", output: "清晰的工作顺序与阶段取舍。", nextAction: "搭建可执行的工作路径。" },
      { id: "build", title: "搭建", en: "BUILD", input: "目标、优先级、重复工作与协同节点。", evaluate: "哪里缺标准、责任人或下一动作。", decision: "将易出错的交接与重复工作流程化。", output: "Pipeline、SOP、Checklist 与 Next Action。", nextAction: "按照明确节点开始推进。" },
      { id: "execute", title: "执行", en: "EXECUTE", input: "内容计划、合作要求、节点与责任分工。", evaluate: "库存、物流、内容、链接、排期和付款是否就绪。", decision: "识别阻塞并对接相应 Owner。", output: "发布、上线或已经解决的交付问题。", nextAction: "回收数据与执行反馈。" },
      { id: "measure", title: "衡量", en: "MEASURE", input: "平台表现、Audience、Referral Traffic 与订单线索。", evaluate: "曝光、互动、引流、转化和交付可靠性。", decision: "区分表面增长与有业务价值的结果。", output: "可追踪的表现记录与复盘结论。", nextAction: "调整下一轮优先级。" },
      { id: "iterate", title: "迭代", en: "ITERATE", input: "表现记录、项目异常与合作反馈。", evaluate: "哪些内容、渠道与合作值得继续。", decision: "保留有效机制，修正低效环节和筛选标准。", output: "更新后的内容方向、SOP 与合作判断。", nextAction: "进入下一轮诊断与执行。" },
    ],
    pipeline: [
      { id: "discover", title: "发现", en: "DISCOVER", text: "明确受众与内容方向，开发美国 Creator，持续处理回复。", output: "相关候选对象", stages: "受众 / 内容 / 开发" },
      { id: "validate", title: "验证", en: "VALIDATE", text: "审核 Audience、数据真实性、内容质量与报价，判断推进、谈价或 PASS。", output: "有依据的合作判断", stages: "筛选 / 商业判断" },
      { id: "structure", title: "确定合作", en: "STRUCTURE", text: "明确合作条件、选品、寄样安排与交付要求。", output: "可执行的合作约定", stages: "谈判 / 选品寄样" },
      { id: "deliver", title: "交付", en: "DELIVER", text: "推进物流与拍摄，审核内容，核对链接和排期并跟进上线。", output: "发布内容与追踪记录", stages: "物流 / 审核 / 上线 / Tracking" },
      { id: "close", title: "闭环", en: "CLOSE", text: "回收数据、推进付款，并判断长期合作价值。", output: "结算与下一轮合作决定", stages: "数据回收 / 付款 / 再合作判断" },
    ],
  },
};
export type Dictionary = typeof zh;
